### ISSUE TITLE
[ Enhancement ] For future search purposes, request to get tags list should include a query param named "REQUESTED_TAG" 

### ISSUE THREAD

**Issue by drorrose** [greenpress/admin-panel#27]
The purpose of this query param is to identify whether all tags are required (value will be "all") or only public tags (value will be "public"). If the user is not an admin or an editor, sending "all" will return the same tags list as if "public" was sent.

Further details by @davidmeirlevy:
About the feature:

The motivation:
editors who want to search tags, should do it, even for non-public posts, and without cached results.

Steps to develop:

Add new route for tags search.
Available for editors only.
Should return tags, without counts, and without cache.
Handle search posts by tags on another issue.

**Comment by davidmeirlevy** [comment]
Queries should be sent as a query params, not at the headers.

About the feature:

The motivation:
editors who want to search tags, should do it, even for non-public posts, and without cached results.

Steps to develop:
1. Add new route for tags search.
2. Available for editors only.
3. Should return tags, without counts, and without cache.

Handle search posts by tags on another issue.

**Comment by davidmeirlevy** [comment]
@drorrose this issue doesn't belong to the admin panel.
it belongs to the content-service.
