### ISSUE TITLE
[Feature] add alignment to WYSIWYG

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/admin-panel#39]
add the ability to align content in WYSIWYG

scenario:
1. go to any page with WYSIWYG (edit category / post).
2. the WYSIWYG doesn't have alignment options.

The WYSIWYG is built on CKEditor, inside a component named GPEditor.

**Comment by benlaniado** [comment]
The editor is using `@ckeditor/ckeditor5-build-classic` the classic build of the editor that doesn't contain the alignment plugin.
We can switch to [Build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html), fork `@ckeditor/ckeditor5-build-classic` and then [adding the plugin to the build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build), or we can use [this fork](https://github.com/leehyunggeun/ckeditor5-build-classic-alignment.git) with the alignment plugin inside. [see here](https://github.com/LeeHyungGeun/ckeditor5-build-classic-alignment/blob/master/src/ckeditor.js#L57).

I think building the editor from the source will just add noise to this project. So I recommend either using [this fork](https://github.com/leehyunggeun/ckeditor5-build-classic-alignment.git) or a similar one. or maybe creating a fork something like `@greenpress/ckeditor5-build-classic`.

What do you think?

**Comment by davidmeirlevy** [comment]
I think the best way is to fork the fork you've shown, so we can later control the plugins separately.
I remember that on the first place I use some kind of fork like that, but it made some issues with useless plugins, and language support.

**Comment by davidmeirlevy** [comment]
also, the "classic" design is not something we want to keep forever, so it's better to just create another "editor" component repository that returns a component.
currently, we can go for the classic theme of ckeditor5, and add some relevant plugins.

**Comment by davidmeirlevy** [comment]
I'm closing the issue here. let's create a customized version here:
https://github.com/greenpress/gp-editor/issues/2

**Comment by benlaniado** [comment]
I'll do it there !
