### ISSUE TITLE
[Feature] set posts drafts using the drafts service API

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/admin-panel#48]
use the drafts service API to set and get posts drafts.
the query will get: {context: 'post', contextId: postId || (empty)}

**Comment by itays123** [comment]
This isn't top priority at the moment since we don't have access to the drafts service yet

**Comment by davidmeirlevy** [comment]
As a developer you can use the branches and service that are under development, and call them locally from the admin panel.

**Comment by itays123** [comment]
Ok. First I'll create a useDraft() hook for us to use.

**Comment by davidmeirlevy** [comment]
There's already a composition for it.. currently store the draft in local storage.. so just change it to use the drafts service (with fallback to local storage).

**Comment by davidmeirlevy** [comment]
no..  drafts should be auto-saved on every page in the admin panel, for all contexts.
maybe add some defer for 5-10 seconds, but it should definitely be automatic, like an composing a mail on gmail.

**Comment by itays123** [comment]
So I'll just update the existing composition. Got it

**Comment by davidmeirlevy** [comment]
note that the existing composition store to local storage on every keyboard click, so add some "debounce" or something.

**Comment by itays123** [comment]
I updated and refactored all required code. The "debounce" is the only thing left to do
